<?php
return array(
	'title'      => esc_html__( 'Header Setting', 'transida' ),
	'id'         => 'headers_setting',
	'desc'       => '',
	'subsection' => false,
	'fields'     => array(
		array(
			'id'      => 'header_source_type',
			'type'    => 'button_set',
			'title'   => esc_html__( 'Header Source Type', 'transida' ),
			'options' => array(
				'd' => esc_html__( 'Default', 'transida' ),
				'e' => esc_html__( 'Elementor', 'transida' ),
			),
			'default' => 'd',
		),
		array(
			'id'       => 'header_elementor_template',
			'type'     => 'select',
			'title'    => __( 'Template', 'transida' ),
			'data'     => 'posts',
			'args'     => [
				'post_type' => [ 'elementor_library' ],
				'posts_per_page'	=> -1
			],
			'required' => [ 'header_source_type', '=', 'e' ],
		),
		array(
			'id'       => 'header_style_section_start',
			'type'     => 'section',
			'indent'      => true,
			'title'    => esc_html__( 'Header Settings', 'transida' ),
			'required' => array( 'header_source_type', '=', 'd' ),
		),
		array(
		    'id'       => 'header_style_settings',
		    'type'     => 'image_select',
		    'title'    => esc_html__( 'Choose Header Styles', 'transida' ),
		    'subtitle' => esc_html__( 'Choose Header Styles', 'transida' ),
		    'options'  => array(

			    'header_v1'  => array(
				    'alt' => esc_html__( 'Header Style 1', 'transida' ),
				    'img' => get_template_directory_uri() . '/assets/images/redux/header/header1.png',
			    ),
			    'header_v2'  => array(
				    'alt' => esc_html__( 'Header Style 2', 'transida' ),
				    'img' => get_template_directory_uri() . '/assets/images/redux/header/header2.png',
			    ),
				'header_v3'  => array(
				    'alt' => esc_html__( 'Header Style 3', 'transida' ),
				    'img' => get_template_directory_uri() . '/assets/images/redux/header/header3.png',
			    ),
			    'header_v4'  => array(
				    'alt' => esc_html__( 'Header Style 4', 'transida' ),
				    'img' => get_template_directory_uri() . '/assets/images/redux/header/header4.png',
			    ),
				'header_v5'  => array(
				    'alt' => esc_html__( 'OnePage Header Style', 'transida' ),
				    'img' => get_template_directory_uri() . '/assets/images/redux/header/header5.png',
			    ),
			),
			'required' => array( 'header_source_type', '=', 'd' ),
			'default' => 'header_v1',
	    ),
		array(
			'id'       => 'header_v1_settings_section_start',
			'type'     => 'section',
			'indent'      => true,
			'title'    => esc_html__( 'Header Style One Settings', 'transida' ),
			'required' => array( 'header_style_settings', '=', 'header_v1' ),
		),
		array(
            'id' => 'normal_logo_show',
            'type' => 'switch',
            'title' => esc_html__('Enable Logo', 'transida'),
            'default' => true,
			'required' => array( 'header_style_settings', '=', 'header_v1' ),
        ),
		array(
			'id'       => 'image_normal_logo',
			'type'     => 'media',
			'url'      => true,
			'title'    => esc_html__( 'Logo', 'transida' ),
			'subtitle' => esc_html__( 'Insert site logo image', 'transida' ),
			'required' => array( 'normal_logo_show', '=', true ),
		),
		array(
			'id'       => 'normal_logo_dimension',
			'type'     => 'dimensions',
			'title'    => esc_html__( 'Logo Dimentions', 'transida' ),
			'subtitle' => esc_html__( 'Select Logo Dimentions', 'transida' ),
			'units'    => array( 'em', 'px', '%' ),
			'default'  => array( 'Width' => '', 'Height' => '' ),
			'required' => array( 'normal_logo_show', '=', true ),
		),
		array(
		    'id'       => 'show_topbar_v1',
		    'type'     => 'switch',
		    'title'    => esc_html__( 'Enable header Topbar', 'transida' ),
		    'desc'     => esc_html__( 'Enable/Disable header Topbar.', 'transida' ),
			'default'  => true,
		    'required' => array( 'header_style_settings', '=', 'header_v1' ),
	    ),
		array(
			'id'    => 'header_v1_social_share',
			'type'  => 'social_media',
			'title' => esc_html__( 'Social Profiles', 'transida' ),
			'required' => array( 'show_topbar_v1', '=', true ),
		),
		array(
            'id' => 'header_v1_search_form',
            'type' => 'switch',
            'title' => esc_html__('Enable Search Form', 'transida'),
            'default' => true,
			'required' => array( 'show_topbar_v1', '=', true ),
        ),
		array(
		    'id'       => 'phone_no_v1',
		    'type'     => 'text',
		    'title'    => esc_html__( 'Phone Number', 'transida' ),
		    'desc'     => esc_html__( 'Enter The Phone Number', 'transida' ),
			'required' => array( 'show_topbar_v1', '=', true ),
	    ),
		array(
		    'id'       => 'signin_title_v1',
		    'type'     => 'text',
		    'title'    => esc_html__( 'Button Title', 'transida' ),
		    'desc'     => esc_html__( 'Enter The Button Title', 'transida' ),
			'required' => array( 'header_style_settings', '=', 'header_v1' ),
	    ),
		array(
		    'id'       => 'signin_link_v1',
		    'type'     => 'text',
		    'title'    => esc_html__( 'Button Link', 'transida' ),
		    'desc'     => esc_html__( 'Enter The Button Link', 'transida' ),
			'required' => array( 'header_style_settings', '=', 'header_v1' ),
	    ),
		array(
            'id' => 'show_hidden_sidebar_v1',
            'type' => 'switch',
            'title' => esc_html__('Enable Sidebar Information', 'transida'),
            'default' => true,
			'required' => array( 'header_style_settings', '=', 'header_v1' ),
        ),
		array(
		    'id'       => 'sidebar_content_v1',
		    'type'     => 'textarea',
		    'title'    => esc_html__( 'Sidebar Content', 'transida' ),
		    'desc'     => esc_html__( 'Enter The Sidebar Content', 'transida' ),
			'required' => array( 'show_hidden_sidebar_v1', '=', true ),
	    ),
		array(
			'id'       => 'pdf_img_v1',
			'type'     => 'media',
			'url'      => true,
			'title'    => esc_html__( 'PDF Image', 'transida' ),
			'required' => array( 'show_hidden_sidebar_v1', '=', true ),
		),
		array(
		    'id'       => 'pdf_title_v1',
		    'type'     => 'text',
		    'title'    => esc_html__( 'PDF Title', 'transida' ),
		    'desc'     => esc_html__( 'Enter The PDF Title', 'transida' ),
			'required' => array( 'show_hidden_sidebar_v1', '=', true ),
	    ),
		array(
			'id'       => 'pdf_img_v2',
			'type'     => 'media',
			'url'      => true,
			'title'    => esc_html__( 'PDF Image V2', 'transida' ),
			'required' => array( 'show_hidden_sidebar_v1', '=', true ),
		),
		array(
		    'id'       => 'pdf_title_v2',
		    'type'     => 'text',
		    'title'    => esc_html__( 'PDF Title', 'transida' ),
		    'desc'     => esc_html__( 'Enter The PDF Title', 'transida' ),
			'required' => array( 'show_hidden_sidebar_v1', '=', true ),
	    ),
		array(
		    'id'       => 'sidebar_address_v1',
		    'type'     => 'textarea',
		    'title'    => esc_html__( 'Address', 'transida' ),
		    'desc'     => esc_html__( 'Enter The Address', 'transida' ),
			'required' => array( 'show_hidden_sidebar_v1', '=', true ),
	    ),
		array(
		    'id'       => 'sidebar_phone_no_v1',
		    'type'     => 'textarea',
		    'title'    => esc_html__( 'Phone Number', 'transida' ),
		    'desc'     => esc_html__( 'Enter The Phone Number', 'transida' ),
			'required' => array( 'show_hidden_sidebar_v1', '=', true ),
	    ),
		array(
		    'id'       => 'sidebar_email_address_v1',
		    'type'     => 'textarea',
		    'title'    => esc_html__( 'Email Address', 'transida' ),
		    'desc'     => esc_html__( 'Enter The Email Address', 'transida' ),
			'required' => array( 'show_hidden_sidebar_v1', '=', true ),
	    ),
		array(
		    'id'       => 'sidebar_btn_title_v1',
		    'type'     => 'text',
		    'title'    => esc_html__( 'Button Title', 'transida' ),
		    'desc'     => esc_html__( 'Enter The Button Title', 'transida' ),
			'required' => array( 'show_hidden_sidebar_v1', '=', true ),
	    ),
		array(
		    'id'       => 'sidebar_btn_link_v1',
		    'type'     => 'text',
		    'title'    => esc_html__( 'Button Link', 'transida' ),
		    'desc'     => esc_html__( 'Enter The Button Link', 'transida' ),
			'required' => array( 'show_hidden_sidebar_v1', '=', true ),
	    ),
		array(
            'id' => 'Show_search_popup_form_v1',
            'type' => 'switch',
            'title' => esc_html__('Enable Search Popup', 'transida'),
            'default' => true,
			'required' => array( 'show_hidden_sidebar_v1', '=', true ),
        ),
		/***********************************************************************
								Header Version 2 Start
		************************************************************************/
		array(
			'id'       => 'header_v2_settings_section_start',
			'type'     => 'section',
			'indent'      => true,
			'title'    => esc_html__( 'Header Style Two Settings', 'transida' ),
			'required' => array( 'header_style_settings', '=', 'header_v2' ),
		),
		array(
            'id' => 'normal_logo_show2',
            'type' => 'switch',
            'title' => esc_html__('Enable Logo', 'transida'),
            'default' => true,
			'required' => array( 'header_style_settings', '=', 'header_v2' ),
        ),
		array(
			'id'       => 'image_normal_logo2',
			'type'     => 'media',
			'url'      => true,
			'title'    => esc_html__( 'Logo', 'transida' ),
			'subtitle' => esc_html__( 'Insert site logo image', 'transida' ),
			'required' => array( 'normal_logo_show2', '=', true ),
		),
		array(
			'id'       => 'normal_logo_dimension2',
			'type'     => 'dimensions',
			'title'    => esc_html__( 'Logo Dimentions', 'transida' ),
			'subtitle' => esc_html__( 'Select Logo Dimentions', 'transida' ),
			'units'    => array( 'em', 'px', '%' ),
			'default'  => array( 'Width' => '', 'Height' => '' ),
			'required' => array( 'normal_logo_show2', '=', true ),
		),
		array(
		    'id'       => 'show_topbar_v2',
		    'type'     => 'switch',
		    'title'    => esc_html__( 'Enable header Topbar', 'transida' ),
		    'desc'     => esc_html__( 'Enable/Disable header Topbar.', 'transida' ),
			'default'  => true,
		    'required' => array( 'header_style_settings', '=', 'header_v2' ),
	    ),
		array(
			'id'    => 'header_v2_social_share',
			'type'  => 'social_media',
			'title' => esc_html__( 'Social Profiles', 'transida' ),
			'required' => array( 'show_topbar_v2', '=', true ),
		),
		array(
            'id' => 'header_v2_search_form',
            'type' => 'switch',
            'title' => esc_html__('Enable Search Form', 'transida'),
            'default' => true,
			'required' => array( 'show_topbar_v2', '=', true ),
        ),
		array(
		    'id'       => 'phone_no_v2',
		    'type'     => 'text',
		    'title'    => esc_html__( 'Phone Number', 'transida' ),
		    'desc'     => esc_html__( 'Enter The Phone Number', 'transida' ),
			'required' => array( 'show_topbar_v2', '=', true ),
	    ),
		array(
		    'id'       => 'email_address_v2',
		    'type'     => 'text',
		    'title'    => esc_html__( 'Email Address', 'transida' ),
		    'desc'     => esc_html__( 'Enter The Email Address', 'transida' ),
			'required' => array( 'show_topbar_v2', '=', true ),
	    ),
		array(
		    'id'       => 'quote_btn_title_v2',
		    'type'     => 'text',
		    'title'    => esc_html__( 'Quote Button Title', 'transida' ),
		    'desc'     => esc_html__( 'Enter The Quote Button Title', 'transida' ),
			'required' => array( 'header_style_settings', '=', 'header_v2' ),
	    ),
		array(
		    'id'       => 'quote_btn_link_v2',
		    'type'     => 'text',
		    'title'    => esc_html__( 'Quote Button Link', 'transida' ),
		    'desc'     => esc_html__( 'Enter The Quote Button Link', 'transida' ),
			'required' => array( 'header_style_settings', '=', 'header_v2' ),
	    ),
		array(
		    'id'       => 'signin_title_v2',
		    'type'     => 'text',
		    'title'    => esc_html__( 'Button Title', 'transida' ),
		    'desc'     => esc_html__( 'Enter The Sign In Button Title', 'transida' ),
			'required' => array( 'header_style_settings', '=', 'header_v2' ),
	    ),
		array(
		    'id'       => 'signin_link_v2',
		    'type'     => 'text',
		    'title'    => esc_html__( 'Button Link', 'transida' ),
		    'desc'     => esc_html__( 'Enter The Sign In Button Link', 'transida' ),
			'required' => array( 'header_style_settings', '=', 'header_v2' ),
	    ),
		array(
            'id' => 'Show_search_popup_form_v2',
            'type' => 'switch',
            'title' => esc_html__('Enable Search Popup', 'transida'),
            'default' => true,
			'required' => array( 'header_style_settings', '=', 'header_v2' ),
        ),
		/***********************************************************************
								Header Version 3 Start
		************************************************************************/
		array(
			'id'       => 'header_v3_settings_section_start',
			'type'     => 'section',
			'indent'      => true,
			'title'    => esc_html__( 'Header Style Three Settings', 'transida' ),
			'required' => array( 'header_style_settings', '=', 'header_v3' ),
		),
		array(
            'id' => 'normal_logo_show3',
            'type' => 'switch',
            'title' => esc_html__('Enable Logo', 'transida'),
            'default' => true,
			'required' => array( 'header_style_settings', '=', 'header_v3' ),
        ),
		array(
			'id'       => 'image_normal_logo3',
			'type'     => 'media',
			'url'      => true,
			'title'    => esc_html__( 'Logo', 'transida' ),
			'subtitle' => esc_html__( 'Insert site logo image', 'transida' ),
			'required' => array( 'normal_logo_show3', '=', true ),
		),
		array(
			'id'       => 'normal_logo_dimension3',
			'type'     => 'dimensions',
			'title'    => esc_html__( 'Logo Dimentions', 'transida' ),
			'subtitle' => esc_html__( 'Select Logo Dimentions', 'transida' ),
			'units'    => array( 'em', 'px', '%' ),
			'required' => array( 'normal_logo_show3', '=', true ),
		),
		array(
		    'id'       => 'show_topbar_v3',
		    'type'     => 'switch',
		    'title'    => esc_html__( 'Enable header Topbar', 'transida' ),
		    'desc'     => esc_html__( 'Enable/Disable header Topbar.', 'transida' ),
			'default'  => true,
		    'required' => array( 'header_style_settings', '=', 'header_v3' ),
	    ),
		array(
		    'id'       => 'signin_title_v3',
		    'type'     => 'text',
		    'title'    => esc_html__( 'Button Title', 'transida' ),
		    'desc'     => esc_html__( 'Enter The Sign In Button Title', 'transida' ),
			'required' => array( 'show_topbar_v3', '=', true ),
	    ),
		array(
		    'id'       => 'signin_link_v3',
		    'type'     => 'text',
		    'title'    => esc_html__( 'Button Link', 'transida' ),
		    'desc'     => esc_html__( 'Enter The Sign In Button Link', 'transida' ),
			'required' => array( 'show_topbar_v3', '=', true ),
	    ),
		array(
            'id' => 'header_v3_search_form',
            'type' => 'switch',
            'title' => esc_html__('Enable Search Form', 'transida'),
            'default' => true,
			'required' => array( 'show_topbar_v3', '=', true ),
        ),
		array(
		    'id'       => 'pages_link_v3',
		    'type'     => 'textarea',
		    'title'    => esc_html__( 'Top Bar Menu', 'transida' ),
		    'desc'     => esc_html__( 'Enter The Top Bar Menu', 'transida' ),
			'required' => array( 'show_topbar_v3', '=', true ),
	    ),
		array(
			'id'    => 'header_v3_social_share',
			'type'  => 'social_media',
			'title' => esc_html__( 'Social Profiles', 'transida' ),
			'required' => array( 'show_topbar_v3', '=', true ),
		),
		array(
		    'id'       => 'address_v3',
		    'type'     => 'textarea',
		    'title'    => esc_html__( 'Address', 'transida' ),
		    'desc'     => esc_html__( 'Enter The Address', 'transida' ),
			'required' => array( 'header_style_settings', '=', 'header_v3' ),
	    ),
		array(
		    'id'       => 'opening_hours_v3',
		    'type'     => 'textarea',
		    'title'    => esc_html__( 'Opening Hours', 'transida' ),
		    'desc'     => esc_html__( 'Enter The Opening Hours', 'transida' ),
			'required' => array( 'header_style_settings', '=', 'header_v3' ),
	    ),
		array(
		    'id'       => 'phone_no_v3',
		    'type'     => 'text',
		    'title'    => esc_html__( 'Phone Number', 'transida' ),
		    'desc'     => esc_html__( 'Enter The Phone Number', 'transida' ),
			'required' => array( 'header_style_settings', '=', 'header_v3' ),
	    ),
		array(
		    'id'       => 'email_address_v3',
		    'type'     => 'text',
		    'title'    => esc_html__( 'Email Address', 'transida' ),
		    'desc'     => esc_html__( 'Enter The Email Address', 'transida' ),
			'required' => array( 'header_style_settings', '=', 'header_v3' ),
	    ),
		array(
		    'id'       => 'quote_btn_title_v3',
		    'type'     => 'text',
		    'title'    => esc_html__( 'Quote Button Title', 'transida' ),
		    'desc'     => esc_html__( 'Enter The Quote Button Title', 'transida' ),
			'required' => array( 'header_style_settings', '=', 'header_v3' ),
	    ),
		array(
		    'id'       => 'quote_btn_link_v3',
		    'type'     => 'text',
		    'title'    => esc_html__( 'Quote Button Link', 'transida' ),
		    'desc'     => esc_html__( 'Enter The Quote Button Link', 'transida' ),
			'required' => array( 'header_style_settings', '=', 'header_v3' ),
	    ),
		array(
		    'id'       => 'apple_link_v3',
		    'type'     => 'text',
		    'title'    => esc_html__( 'Apple External Link', 'transida' ),
		    'desc'     => esc_html__( 'Enter The Apple External  Link', 'transida' ),
			'required' => array( 'header_style_settings', '=', 'header_v3' ),
	    ),
		array(
		    'id'       => 'android_link_v3',
		    'type'     => 'text',
		    'title'    => esc_html__( 'Android Link', 'transida' ),
		    'desc'     => esc_html__( 'Enter The Android Link', 'transida' ),
			'required' => array( 'header_style_settings', '=', 'header_v3' ),
	    ),
		array(
            'id' => 'show_hidden_sidebar_v3',
            'type' => 'switch',
            'title' => esc_html__('Enable Sidebar Information', 'transida'),
            'default' => true,
			'required' => array( 'header_style_settings', '=', 'header_v3' ),
        ),
		array(
		    'id'       => 'sidebar_content_v3',
		    'type'     => 'textarea',
		    'title'    => esc_html__( 'Sidebar Content', 'transida' ),
		    'desc'     => esc_html__( 'Enter The Sidebar Content', 'transida' ),
			'required' => array( 'show_hidden_sidebar_v3', '=', true ),
	    ),
		array(
			'id'       => 'pdf_img_v3',
			'type'     => 'media',
			'url'      => true,
			'title'    => esc_html__( 'PDF Image', 'transida' ),
			'required' => array( 'show_hidden_sidebar_v3', '=', true ),
		),
		array(
		    'id'       => 'pdf_title_v3',
		    'type'     => 'text',
		    'title'    => esc_html__( 'PDF Title', 'transida' ),
		    'desc'     => esc_html__( 'Enter The PDF Title', 'transida' ),
			'required' => array( 'show_hidden_sidebar_v3', '=', true ),
	    ),
		array(
			'id'       => 'pdf_img_v4',
			'type'     => 'media',
			'url'      => true,
			'title'    => esc_html__( 'PDF Image V2', 'transida' ),
			'required' => array( 'show_hidden_sidebar_v3', '=', true ),
		),
		array(
		    'id'       => 'pdf_title_v4',
		    'type'     => 'text',
		    'title'    => esc_html__( 'PDF Title', 'transida' ),
		    'desc'     => esc_html__( 'Enter The PDF Title', 'transida' ),
			'required' => array( 'show_hidden_sidebar_v3', '=', true ),
	    ),
		array(
		    'id'       => 'sidebar_address_v3',
		    'type'     => 'textarea',
		    'title'    => esc_html__( 'Address', 'transida' ),
		    'desc'     => esc_html__( 'Enter The Address', 'transida' ),
			'required' => array( 'show_hidden_sidebar_v3', '=', true ),
	    ),
		array(
		    'id'       => 'sidebar_phone_no_v3',
		    'type'     => 'textarea',
		    'title'    => esc_html__( 'Phone Number', 'transida' ),
		    'desc'     => esc_html__( 'Enter The Phone Number', 'transida' ),
			'required' => array( 'show_hidden_sidebar_v3', '=', true ),
	    ),
		array(
		    'id'       => 'sidebar_email_address_v3',
		    'type'     => 'textarea',
		    'title'    => esc_html__( 'Email Address', 'transida' ),
		    'desc'     => esc_html__( 'Enter The Email Address', 'transida' ),
			'required' => array( 'show_hidden_sidebar_v3', '=', true ),
	    ),
		array(
		    'id'       => 'sidebar_btn_title_v3',
		    'type'     => 'text',
		    'title'    => esc_html__( 'Button Title', 'transida' ),
		    'desc'     => esc_html__( 'Enter The Button Title', 'transida' ),
			'required' => array( 'show_hidden_sidebar_v3', '=', true ),
	    ),
		array(
		    'id'       => 'sidebar_btn_link_v3',
		    'type'     => 'text',
		    'title'    => esc_html__( 'Button Link', 'transida' ),
		    'desc'     => esc_html__( 'Enter The Button Link', 'transida' ),
			'required' => array( 'show_hidden_sidebar_v3', '=', true ),
	    ),
		array(
            'id' => 'Show_search_popup_form_v3',
            'type' => 'switch',
            'title' => esc_html__('Enable Search Popup', 'transida'),
            'default' => true,
			'required' => array( 'show_hidden_sidebar_v3', '=', true ),
        ),
		/***********************************************************************
								Header Version 4 Start
		************************************************************************/
		array(
			'id'       => 'header_v4_settings_section_start',
			'type'     => 'section',
			'indent'      => true,
			'title'    => esc_html__( 'Header Style Four Settings', 'transida' ),
			'required' => array( 'header_style_settings', '=', 'header_v4' ),
		),
		array(
            'id' => 'normal_logo_show4',
            'type' => 'switch',
            'title' => esc_html__('Enable Logo', 'transida'),
            'default' => true,
			'required' => array( 'header_style_settings', '=', 'header_v4' ),
        ),
		array(
			'id'       => 'image_normal_logo4',
			'type'     => 'media',
			'url'      => true,
			'title'    => esc_html__( 'Insert Logo', 'transida' ),
			'subtitle' => esc_html__( 'Insert Site logo image', 'transida' ),
			'required' => array( 'normal_logo_show4', '=', true ),
		),
		array(
			'id'       => 'normal_logo_dimension4',
			'type'     => 'dimensions',
			'title'    => esc_html__( 'Logo Dimentions', 'transida' ),
			'subtitle' => esc_html__( 'Select Logo Dimentions', 'transida' ),
			'units'    => array( 'em', 'px', '%' ),
			'default'  => array( 'Width' => '', 'Height' => '' ),
			'required' => array( 'normal_logo_show4', '=', true ),
		),
		array(
            'id' => 'normal_logo_show5',
            'type' => 'switch',
            'title' => esc_html__('Enable Mobile Logo', 'transida'),
            'default' => true,
			'required' => array( 'header_style_settings', '=', 'header_v5' ),
        ),
		array(
			'id'       => 'image_normal_logo5',
			'type'     => 'media',
			'url'      => true,
			'title'    => esc_html__( 'Insert Mobile Logo', 'transida' ),
			'subtitle' => esc_html__( 'Insert Site Mobile logo image', 'transida' ),
			'required' => array( 'normal_logo_show5', '=', true ),
		),
		array(
			'id'       => 'normal_logo_dimension5',
			'type'     => 'dimensions',
			'title'    => esc_html__( 'Mobile Logo Dimentions', 'transida' ),
			'subtitle' => esc_html__( 'Select Mobile Logo Dimentions', 'transida' ),
			'units'    => array( 'em', 'px', '%' ),
			'default'  => array( 'Width' => '', 'Height' => '' ),
			'required' => array( 'normal_logo_show5', '=', true ),
		),
		array(
		    'id'       => 'show_topbar_v4',
		    'type'     => 'switch',
		    'title'    => esc_html__( 'Enable header Topbar', 'transida' ),
		    'desc'     => esc_html__( 'Enable/Disable header Topbar.', 'transida' ),
			'default'  => true,
		    'required' => array( 'header_style_settings', '=', 'header_v4' ),
	    ),
		array(
		    'id'       => 'signin_title_v4',
		    'type'     => 'text',
		    'title'    => esc_html__( 'Button Title', 'transida' ),
		    'desc'     => esc_html__( 'Enter The Sign In Button Title', 'transida' ),
			'required' => array( 'show_topbar_v4', '=', true ),
	    ),
		array(
		    'id'       => 'signin_link_v4',
		    'type'     => 'text',
		    'title'    => esc_html__( 'Button Link', 'transida' ),
		    'desc'     => esc_html__( 'Enter The Sign In Button Link', 'transida' ),
			'required' => array( 'show_topbar_v4', '=', true ),
	    ),
		array(
            'id' => 'header_v4_search_form',
            'type' => 'switch',
            'title' => esc_html__('Enable Search Form', 'transida'),
            'default' => true,
			'required' => array( 'show_topbar_v4', '=', true ),
        ),
		array(
		    'id'       => 'pages_link_v4',
		    'type'     => 'textarea',
		    'title'    => esc_html__( 'Top Bar Menu', 'transida' ),
		    'desc'     => esc_html__( 'Enter The Top Bar Menu', 'transida' ),
			'required' => array( 'show_topbar_v4', '=', true ),
	    ),
		array(
			'id'    => 'header_v4_social_share',
			'type'  => 'social_media',
			'title' => esc_html__( 'Social Profiles', 'transida' ),
			'required' => array( 'show_topbar_v4', '=', true ),
		),
		array(
		    'id'       => 'phone_title_v4',
		    'type'     => 'text',
		    'title'    => esc_html__( 'Phone Title', 'transida' ),
		    'desc'     => esc_html__( 'Enter The Phone Title', 'transida' ),
			'required' => array( 'header_style_settings', '=', 'header_v4' ),
	    ),
		array(
		    'id'       => 'phone_no_v4',
		    'type'     => 'text',
		    'title'    => esc_html__( 'Phone Number', 'transida' ),
		    'desc'     => esc_html__( 'Enter The Phone Number', 'transida' ),
			'required' => array( 'header_style_settings', '=', 'header_v4' ),
	    ),
		array(
            'id' => 'Show_search_popup_form_v4',
            'type' => 'switch',
            'title' => esc_html__('Enable Search Popup', 'transida'),
            'default' => true,
			'required' => array( 'show_hidden_sidebar_v4', '=', true ),
        ),
		
		
		/***********************************************************************
								Header Version 5 Start
		************************************************************************/
		array(
			'id'       => 'header_v5_settings_section_start',
			'type'     => 'section',
			'indent'      => true,
			'title'    => esc_html__( 'OnePage Header Style Settings', 'transida' ),
			'required' => array( 'header_style_settings', '=', 'header_v5' ),
		),
		array(
            'id' => 'normal_logo_show6',
            'type' => 'switch',
            'title' => esc_html__('Enable Logo', 'transida'),
            'default' => true,
			'required' => array( 'header_style_settings', '=', 'header_v5' ),
        ),
		array(
			'id'       => 'image_normal_logo6',
			'type'     => 'media',
			'url'      => true,
			'title'    => esc_html__( 'Logo', 'transida' ),
			'subtitle' => esc_html__( 'Insert site logo image', 'transida' ),
			'required' => array( 'normal_logo_show6', '=', true ),
		),
		array(
			'id'       => 'normal_logo_dimension6',
			'type'     => 'dimensions',
			'title'    => esc_html__( 'Logo Dimentions', 'transida' ),
			'subtitle' => esc_html__( 'Select Logo Dimentions', 'transida' ),
			'units'    => array( 'em', 'px', '%' ),
			'default'  => array( 'Width' => '', 'Height' => '' ),
			'required' => array( 'normal_logo_show6', '=', true ),
		),
		array(
		    'id'       => 'show_topbar_v5',
		    'type'     => 'switch',
		    'title'    => esc_html__( 'Enable header Topbar', 'transida' ),
		    'desc'     => esc_html__( 'Enable/Disable header Topbar.', 'transida' ),
			'default'  => true,
		    'required' => array( 'header_style_settings', '=', 'header_v5' ),
	    ),
		array(
			'id'    => 'header_v5_social_share',
			'type'  => 'social_media',
			'title' => esc_html__( 'Social Profiles', 'transida' ),
			'required' => array( 'show_topbar_v5', '=', true ),
		),
		array(
            'id' => 'header_v5_search_form',
            'type' => 'switch',
            'title' => esc_html__('Enable Search Form', 'transida'),
            'default' => true,
			'required' => array( 'show_topbar_v5', '=', true ),
        ),
		array(
		    'id'       => 'phone_no_v5',
		    'type'     => 'text',
		    'title'    => esc_html__( 'Phone Number', 'transida' ),
		    'desc'     => esc_html__( 'Enter The Phone Number', 'transida' ),
			'required' => array( 'show_topbar_v5', '=', true ),
	    ),
		array(
		    'id'       => 'signin_title_v5',
		    'type'     => 'text',
		    'title'    => esc_html__( 'Button Title', 'transida' ),
		    'desc'     => esc_html__( 'Enter The Button Title', 'transida' ),
			'required' => array( 'header_style_settings', '=', 'header_v5' ),
	    ),
		array(
		    'id'       => 'signin_link_v5',
		    'type'     => 'text',
		    'title'    => esc_html__( 'Button Link', 'transida' ),
		    'desc'     => esc_html__( 'Enter The Button Link', 'transida' ),
			'required' => array( 'header_style_settings', '=', 'header_v5' ),
	    ),
		array(
            'id' => 'show_hidden_sidebar_v5',
            'type' => 'switch',
            'title' => esc_html__('Enable Sidebar Information', 'transida'),
            'default' => true,
			'required' => array( 'header_style_settings', '=', 'header_v5' ),
        ),
		array(
		    'id'       => 'sidebar_content_v5',
		    'type'     => 'textarea',
		    'title'    => esc_html__( 'Sidebar Content', 'transida' ),
		    'desc'     => esc_html__( 'Enter The Sidebar Content', 'transida' ),
			'required' => array( 'show_hidden_sidebar_v5', '=', true ),
	    ),
		array(
			'id'       => 'pdf_img_v6',
			'type'     => 'media',
			'url'      => true,
			'title'    => esc_html__( 'PDF Image', 'transida' ),
			'required' => array( 'show_hidden_sidebar_v5', '=', true ),
		),
		array(
		    'id'       => 'pdf_title_v6',
		    'type'     => 'text',
		    'title'    => esc_html__( 'PDF Title', 'transida' ),
		    'desc'     => esc_html__( 'Enter The PDF Title', 'transida' ),
			'required' => array( 'show_hidden_sidebar_v5', '=', true ),
	    ),
		array(
			'id'       => 'pdf_img_v7',
			'type'     => 'media',
			'url'      => true,
			'title'    => esc_html__( 'PDF Image V2', 'transida' ),
			'required' => array( 'show_hidden_sidebar_v5', '=', true ),
		),
		array(
		    'id'       => 'pdf_title_v7',
		    'type'     => 'text',
		    'title'    => esc_html__( 'PDF Title', 'transida' ),
		    'desc'     => esc_html__( 'Enter The PDF Title', 'transida' ),
			'required' => array( 'show_hidden_sidebar_v5', '=', true ),
	    ),
		array(
		    'id'       => 'sidebar_address_v5',
		    'type'     => 'textarea',
		    'title'    => esc_html__( 'Address', 'transida' ),
		    'desc'     => esc_html__( 'Enter The Address', 'transida' ),
			'required' => array( 'show_hidden_sidebar_v5', '=', true ),
	    ),
		array(
		    'id'       => 'sidebar_phone_no_v5',
		    'type'     => 'textarea',
		    'title'    => esc_html__( 'Phone Number', 'transida' ),
		    'desc'     => esc_html__( 'Enter The Phone Number', 'transida' ),
			'required' => array( 'show_hidden_sidebar_v5', '=', true ),
	    ),
		array(
		    'id'       => 'sidebar_email_address_v5',
		    'type'     => 'textarea',
		    'title'    => esc_html__( 'Email Address', 'transida' ),
		    'desc'     => esc_html__( 'Enter The Email Address', 'transida' ),
			'required' => array( 'show_hidden_sidebar_v5', '=', true ),
	    ),
		array(
		    'id'       => 'sidebar_btn_title_v5',
		    'type'     => 'text',
		    'title'    => esc_html__( 'Button Title', 'transida' ),
		    'desc'     => esc_html__( 'Enter The Button Title', 'transida' ),
			'required' => array( 'show_hidden_sidebar_v5', '=', true ),
	    ),
		array(
		    'id'       => 'sidebar_btn_link_v5',
		    'type'     => 'text',
		    'title'    => esc_html__( 'Button Link', 'transida' ),
		    'desc'     => esc_html__( 'Enter The Button Link', 'transida' ),
			'required' => array( 'show_hidden_sidebar_v5', '=', true ),
	    ),
		array(
            'id' => 'Show_search_popup_form_v5',
            'type' => 'switch',
            'title' => esc_html__('Enable Search Popup', 'transida'),
            'default' => true,
			'required' => array( 'show_hidden_sidebar_v5', '=', true ),
        ),
		array(
			'id'       => 'header_style_section_end',
			'type'     => 'section',
			'indent'      => false,
			'required' => [ 'header_source_type', '=', 'd' ],
		),
	),
);
